- hosts: localhost
  user: simon
  sudo: True
  serial: 1
  tasks:

  - name: Update System
    action: apt update-cache=yes

  - name: Upgrade System
    action: apt upgrade=dist
    
  - name: Install Required Software
    action: apt pkg={{item}} state=present
    with_items:
    - htop
