- hosts: localhost
  user: simon
  sudo: True
  serial: 1
  tasks:

  - name: Add suricata repository
    apt_repository: repo='ppa:oisf/suricata-stable'
  
  - name: Update System
    action: apt update-cache=yes
    
  - name: Install Required Software
    action: apt pkg={{item}} state=present
    with_items:
    - suricata

  - name: Copy configuration file
    copy: src=config/suricata.yaml dest=/etc/suricata/suricata.yaml mode=644

  - name: Start Suricata
    command: 'sudo suricata -c /etc/suricata/suricata.yaml -i eth0 --init-errors-fatal'

