- hosts: localhost
  user: simon
  sudo: True
  serial: 1
  tasks:

  - name: Add suricata repository
    apt_repository: repo='ppa:oisf/suricata-stable'
  
  - name: Update System
    action: apt update-cache=yes
    
  - name: Install Required Software
    action: apt pkg={{item}} state=present
    with_items:
    - suricata
    - oinkmaster

  - name: Copy Suricata configuration file
    copy: src=config/suricata.yaml dest=/etc/suricata/suricata.yaml mode=644

  - name: Copy Oinkmaster configuration file
    copy: src=config/oinkmaster.conf /etc/oinkmaster.conf

  - name: Run Oinkmaster (Update Rules)
    command: 'sudo oinkmaster -C /etc/oinkmaster.conf -o /etc/suricata/rules'

  - name: Add above task as cronjob
    cron: name="Oinkmaster" minute="45" hour="8" job="sudo oinkmaster -C /etc/oinkmaster.conf -o /etc/suricata/rules'

  - name: Start Suricata
    command: 'sudo suricata -c /etc/suricata/suricarta.yaml -i eth0 --init-errors-fatal'
