- hosts: localhost
  sudo: yes
  become_method: sudo
  serial: 1
  tasks:

  - name: Add suricata repository
    apt_repository: repo='ppa:oisf/suricata-stable'
  
  - name: Update System
    action: apt update-cache=yes
    
  - name: Install Required Software
    action: apt pkg={{item}} state=present
    with_items:
    - suricata
    - oinkmaster

  - name: Copy Suricata configuration file
    copy: src=config/suricata.yaml dest=/etc/suricata/suricata.yaml owner=simon mode=644

  - name: Copy Oinkmaster configuration file
    copy: src=config/oinkmaster.conf dest=/etc/oinkmaster.conf owner=simon mode=644

  - name: Run Oinkmaster (Update Rules)
    command: 'sudo oinkmaster -C /etc/oinkmaster.conf -o /etc/suricata/rules'

  - name: Add above task as cronjob
    cron: name="Oinkmaster" minute="45" hour="8" job="oinkmaster -C /etc/oinkmaster.conf -o /etc/suricata/rules"

  - name: Start Suricata
    command: 'suricata -c /etc/suricata/suricata.yaml -i eth0 --init-errors-fatal -D'
    ignore_errors: yes

  - name: Start Suricata if not started
    service: name=suricata state=started

  - name: Test if Suricata is working or not
    command: 'curl testmyids.com'

  - name: Print Instruction
    debug: msg="Please check /var/log/suricata/fast.log. If you see output like 'GPL', then Suricata is functioning properly"
