- hosts: localhost
  user: simon
  sudo: True
  serial: 1
  tasks:

  - name: Create working directory
    file: path=/home/simon/working state=directory mode=0755
    args:
      chdir: /home/simon/working

  - name: Add Java 8 Repository
    apt_repository: repo='ppa:webupd8team/java'
  
  - name: Add Nginx Repository
    apt_repository: repo='ppa:nginx/development'

  - name: Update System
    action: apt update-cache=yes
    
  - name: Add Elasticsearch GPG key into apt
    shell: 'wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -'
  
  - name: Add the repository definition for Elasticsearch
    shell: 'echo "deb http://packages.elastic.co/elasticsearch/2.x/debian stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-2.x.list'

  - name: Add the repository definition for Kibana
    shell: 'echo "deb http://packages.elastic.co/kibana/4.4/debian stable main" | sudo tee -a /etc/apt/sources.list.d/kibana-4.4.x.list'

  - name: Add the repository definition for logstash
    shell: 'echo "deb http://packages.elastic.co/logstash/2.2/debian stable main" | sudo tee /etc/apt/sources.list.d/logstash-2.2.x.list'

  - name: Accept Java 8 License
    sudo: yes
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - name: Install JRE
    apt: pkg=oracle-java8-installer state=latest update-cache=yes force=yes

  - name: Install Required Software
    action: apt pkg={{item}} state=present
    with_items:
    - nginx
    - elasticsearch
    - kibana
    - unzip
    - apache2-utils
    - logstash

  - name: Run Elasticsearch on bootup
    shell: 'sudo update-rc.d elasticsearch defaults 95 10'

  - name: Run Kibana on bootup
    shell: 'sudo update-rc.d kibana defaults 96 9'

  - name: Run Logstash on bootup
    shell: 'sudo update-rc.d logstash defaults 96 9'

  - name: Remove default Nginx configuration file
    file: path=/etc/nginx/sites-enabled/default state=absent
    ignore_errors: yes

  - name: Remove default Nginx configuration file
    file: path=/etc/nginx/sites-available/default state=absent
    ignore_errors: yes

  - name: Move Nginx configuration file
    copy: src=config/nginx/server dest=/etc/nginx/sites-available/server

  - name: Restart Nginx
    service: name=nginx state=restarted

  - name: Create admin user
    shell: 'htpasswd -c /etc/nginx/htpasswd.users kibanaadmin'

  - name: Download Kibana dashboard
    shell: 'curl -L -O https://download.elastic.co/beats/dashboards/beats-dashboards-1.1.1.zip'

  - name: Create certificate storage
    shell: 'sudo mkdir -p /etc/pki/elk/certs'
    ignore_errors: yes

  - name: Create private key storage
    shell: 'sudo mkdir /etc/pki/elk/private'
    ignore_errors: yes

  - name: Create SSL Certs
    shell: 'sudo openssl req -subj "/CN=simonsong.online/" -x509 -days 3650 -batch -nodes -newkey rsa:4096 -keyout /etc/pki/elk/private/logstash-forwarder.key -out /etc/pki/elk/certs/logstash-forwarder.crt'

  - name: Move logstash configuration file1
    copy: src=config/logstash/02-beats-input.conf dest=/etc/logstash/conf.d/02-beats-input.conf

  - name: Move logstash configuration file2
    copy: src=config/logstash/10-syslog-filter.conf dest=/etc/logstash/conf.d/10-syslog-filter.conf

  - name: Move logstash configuration file3
    copy: src=config/logstash/30-elasticsearch-output.conf dest=/etc/logstash/conf.d/30-elasticsearch-output.conf

  - name: Logstash configtest
    shell: 'sudo service logstash configtest'

  - name: Restart Logstash	
    service: name=logstash state=restarted

